spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:schema_voucher;MODE=MySQL
    username: sa
    password:

  sql:
    init:
      platform: h2
      mode: always
